// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package web

import (
	user2 "github.com/wwq1988/dddsampple/pkg/application/user"
	"github.com/wwq1988/dddsampple/pkg/conf"
	"github.com/wwq1988/dddsampple/pkg/domain/model/user"
	"github.com/wwq1988/dddsampple/pkg/interfaces"
	"github.com/wwq1988/dddsampple/pkg/interfaces/user/facade"
)

// Injectors from wire.go:

func Create() interfaces.Web {
	config := conf.Parse()
	repo := user.New(config)
	service := user2.New(repo)
	facadeFacade := facade.New(service)
	web := New(facadeFacade)
	return web
}
