// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/wwq1988/dddsampple/pkg/conf"
	"github.com/wwq1988/dddsampple/pkg/interfaces"
	"github.com/wwq1988/dddsampple/pkg/server"
)

// Injectors from wire.go:

func CreateServer() *server.Server {
	config := conf.Parse()
	v := interfaces.Webs()
	serverServer := server.New(config, v...)
	return serverServer
}
